"""Specialized skill agent configurations for genius-agent."""

SKILL_AGENTS = {
    "web-browser": {
        "description": "Specialized in browser automation, web scraping, and internet search.",
        "tags": ["browser", "web-crawler", "scraping", "playwright", "web-search"],
    },
    "engineering": {
        "description": "Expert in software engineering, git/github workflows, testing, and system analysis.",
        "tags": [
            "development",
            "git",
            "github",
            "testing",
            "mcp",
            "coding",
            "systems",
            "repository",
            "api-builder",
        ],
    },
    "creative-content": {
        "description": "Creative assistant for design, diagrams, branding, and presentations.",
        "tags": [
            "creative",
            "design",
            "art",
            "diagrams",
            "mermaid",
            "branding",
            "media",
            "presentations",
            "c4",
        ],
    },
    "product-strategy": {
        "description": "Specialized in product management, strategy, user research, and project planning.",
        "tags": ["planning", "strategy", "research", "pm", "brainstorming", "comms"],
    },
    "productivity": {
        "description": "Assistant for document management, office tools, and workspace productivity.",
        "tags": [
            "office",
            "documents",
            "workspace",
            "productivity",
            "google-workspace",
            "jira",
            "handoff",
        ],
    },
    "systems-infra": {
        "description": "Expert in infrastructure, cloud deployment, databases, and system security.",
        "tags": [
            "infrastructure",
            "cloud",
            "database",
            "security",
            "system",
            "workflows",
            "documentation",
        ],
    },
    "frontend-expert": {
        "description": "Specialized in frontend development, UI frameworks, and web technologies documentation.",
        "tags": [
            "frontend",
            "ui",
            "react",
            "nextjs",
            "svelte",
            "vue",
            "css",
            "vite",
            "documentation",
            "web",
        ],
    },
    "backend-expert": {
        "description": "Expert in backend development, APIs, and server-side language documentation.",
        "tags": [
            "backend",
            "api",
            "python",
            "go",
            "rust",
            "java",
            "c",
            "django",
            "fastapi",
            "nodejs",
            "documentation",
        ],
    },
    "database-expert": {
        "description": "Specialized in database management, SQL, NoSQL, and vector database documentation.",
        "tags": [
            "database",
            "sql",
            "nosql",
            "postgres",
            "mongodb",
            "redis",
            "vector-db",
            "documentation",
        ],
    },
    "ai-ml-expert": {
        "description": "Expert in AI, Machine Learning, LLMs, and data science documentation.",
        "tags": [
            "ai",
            "ml",
            "llm",
            "pydantic-ai",
            "pytorch",
            "tensorflow",
            "data-science",
            "documentation",
        ],
    },
    "cloud-infra-expert": {
        "description": "Specialized in cloud platforms, DevOps, and infrastructure-as-code documentation.",
        "tags": [
            "cloud",
            "aws",
            "azure",
            "gcp",
            "docker",
            "terraform",
            "linux",
            "devops",
            "documentation",
        ],
    },
}
