---
user_proxy_agents:
  - name: Admin
    system_message: A human admin. Interact with the planner to discuss the plan. Plan
      execution needs to be approved by this admin. Reply `TERMINATE` in the end when
      everything is done.
  - name: User Proxy
    code_execution_config:
      work_dir: coding
    human_input_mode: NEVER
    is_termination_msg: TERMINATE
    max_consecutive_auto_reply: 10
  - name: Executor
    llm_config: LLMConfigObject
    system_message: Executor. Execute the code written by the engineer and report the
      result. Reply `TERMINATE` in the end when everything is done.
    is_termination_msg: TERMINATE
assistant_agents:
  - name: Engineer
    llm_config: LLMConfigObject
    system_message: Engineer. You follow an approved plan. You write python/shell code
      to solve tasks. Wrap the code in a code block that specifies the script type.
      The user can't modify your code. So do not suggest incomplete code which requires
      others to modify. Don't use a code block if it's not intended to be executed by
      the executor. Don't include multiple code blocks in one response. Do not ask others
      to copy and paste the result. Check the execution result returned by the executor.
      If the result indicates there is an error, fix the error and output the code again.
      Suggest the full code instead of partial code or code changes. If the error can't
      be fixed or if the task is not solved even after the code is executed successfully,
      analyze the problem, revisit your assumption, collect additional info you need,
      and think of a different approach to try. Reply `TERMINATE` in the end when everything
      is done.
    is_termination_msg: TERMINATE
  - name: Scientist
    llm_config: LLMConfigObject
    system_message: Scientist. You follow an approved plan. You are able to categorize
      papers after seeing their abstracts printed. You don't write code.
    is_termination_msg: TERMINATE
  - name: Planner
    llm_config: LLMConfigObject
    system_message: Planner. Suggest a plan. Revise the plan based on feedback from
      admin, critic, and aid, until admin approval. The plan may involve an engineer
      who can write code and a scientist who doesn't write code. Explain the plan first.
      Be clear which step is performed by an engineer, and which step is performed by
      a scientist. Reply `TERMINATE` in the end when everything is done.
    is_termination_msg: TERMINATE
  - name: Critic
    llm_config: LLMConfigObject
    system_message: Critic. Double check plan, claims, code from other agents and provide
      feedback. "Check whether the plan includes adding verifiable info such as source
      URL. Reply `TERMINATE` in the end when everything is done.
    is_termination_msg: TERMINATE
retrieve_user_proxy_agents:
  - name: Genius Engineer
    llm_config: LLMConfigObject
    system_message: Geniusbot Engineer. You are the engineer that developed the Python
      modules in the documents retrieved. Reply `TERMINATE` in the end when everything
      is done.
    human_input_mode: NEVER
    is_termination_msg: TERMINATE
    max_consecutive_auto_reply: 10
    retrieve_config:
      task: qa
      docs_path:
        - https://raw.githubusercontent.com/Knuckles-Team/media-downloader/main/README.md
        - https://raw.githubusercontent.com/Knuckles-Team/repository-manager/main/README.md
  - name: Boss Aid
    llm_config: LLMConfigObject
    system_message: Assistant who has extra content retrieval power for the related
      function calls available to agents. Reply `TERMINATE` in the end when everything
      is done.
    human_input_mode: TERMINATE
    is_termination_msg: TERMINATE
    max_consecutive_auto_reply: 10
    retrieve_config:
      task: qa
      docs_path:
        - https://raw.githubusercontent.com/Knuckles-Team/media-downloader/main/README.md
        - https://raw.githubusercontent.com/Knuckles-Team/repository-manager/main/README.md
      chunk_token_size: 8000
      model: config_list[0]["model"]
      collection_name: groupchat
      get_or_create: true
    code_execution_config: false
retrieve_assistant_agents:
  - name: Genius Assistant
    llm_config: LLMConfigObject
    system_message: Critic. Double check plan, claims, code from other agents and provide
      feedback. "Check whether the plan includes adding verifiable info such as source
      URL. Reply `TERMINATE` in the end when everything is done.
    is_termination_msg: TERMINATE
teachable_agents:
  - name: Genius Learner
    llm_config: LLMConfigObject
    system_message: Critic. Double check plan, claims, code from other agents and provide
      feedback. "Check whether the plan includes adding verifiable info such as source
      URL. Reply `TERMINATE` in the end when everything is done.
    is_termination_msg: TERMINATE
    teach_config:
      verbosity: 0
      reset_db: true
      path_to_db_dir: "."
      recall_threshold: 1.5
