---
seed: 42
temperature: 0.9
config_list:
  - model: yarn-mistral-7b-128k.Q3_K_L
    api_key: NA
    api_base: http://localhost:8080/v1
    api_type: openai
    api_version: v1
  - model: llama-2-7b-chat.ggmlv3.q4_K_S
    api_key: NA
    api_base: http://localhost:8080/v1
    api_type: openai
    api_version: v1
  - model: mistral-7b--instruct-v0.1.Q5_K_S
    api_key: NA
    api_base: http://localhost:8080/v1
    api_type: openai
    api_version: v1
  - model: TheBloke/WizardLM-13B-V1.2-GGML/wizardlm-13b-v1.2.ggmlv3.q2_K.bin
    api_key: NA
    api_base: http://localhost:8080/v1
    api_type: openai
    api_version: v1
  - model: codellama-7b-instruct
    api_key: NA
    api_base: http://localhost:8080/v1
    api_type: openai
    api_version: v1
  - model: gpt-4-32k
    api_key: NA
  - model: gpt-4-32k
    api_key: NA
    api_base: NA
    api_type: azure
    api_version: 2023-06-01-preview
  - model: gpt-4-32k-0314
    api_key: NA
    api_base: NA
    api_type: azure
    api_version: 2023-06-01-preview
filter_dict:
  model:
    - yarn-mistral-7b-128k.Q3_K_L
    - llama-2-7b-chat.ggmlv3.q4_K_S
    - mistral-7b--instruct-v0.1.Q5_K_S
    - TheBloke/WizardLM-13B-V1.2-GGML/wizardlm-13b-v1.2.ggmlv3.q2_K.bin
    - mistral-7b-instruct-v0.1.Q8_0
    - codellama-7b-instruct
request_timeout: 3600
repeat_penalty: 1.1
functions:
  - name: python
    description: run arbitrary python and return the result
    parameters:
      type: object
      properties:
        cell:
          type: string
          description: Valid Python code to execute.
      required:
        - cell
  - name: bash
    description: run a shell script and return the execution result.
    parameters:
      type: object
      properties:
        script:
          type: string
          description: Valid shell script to execute
      required:
        - script
  - name: media_downloader
    description: run media-downloader to download a video or audio from the internet
    parameters:
      type: object
      properties:
        url:
          type: string
          description: Valid url to download
        audio:
          type: bool
          description: This optional argument is used if the link wants to be saved
            as an mp3 or audio only
        directory:
          type: string
          description: Directory to save the video
      required:
        - url
  - name: write_to_file
    description: Use this function to write content to a file
    parameters:
      type: object
      properties:
        filename:
          type: string
          description: The filename to write to
        content:
          type: string
          description: The content to write
      required:
        - filename
        - content
  - name: read_from_file
    description: Use this function to read the content of a file
    parameters:
      type: object
      properties:
        filename:
          type: string
          description: The filename to read from
      required:
        - filename
  - name: read_pdf
    description: Use this function to read the content of a pdf file
    parameters:
      type: object
      properties:
        filename:
          type: string
          description: The filename to read from
      required:
        - filename
  - name: create_directory
    description: Use this function to create a directory
    parameters:
      type: object
      properties:
        directory_path:
          type: string
          description: The directory path to create
      required:
        - directory_path
function_map:
  python: exec_python
  bash: exec_bash
  media_download: exec_media_downloader
  write_to_file: exec_write_to_file
  read_from_file: exec_read_from_file
  create_directory: exec_create_directory